// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAynUBBnEswm2fubg1teLkazxWDow7hpgg',
    appId: '1:282800535881:web:10c6d911c759a75ed48298',
    messagingSenderId: '282800535881',
    projectId: 'migrant-connect',
    authDomain: 'migrant-connect.firebaseapp.com',
    storageBucket: 'migrant-connect.firebasestorage.app',
    measurementId: 'G-TGXCF0S7Z9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNvOW2AGsnnivmHuzujvvq6esI3NGka8k',
    appId: '1:282800535881:android:47489e0cc85cd247d48298',
    messagingSenderId: '282800535881',
    projectId: 'migrant-connect',
    storageBucket: 'migrant-connect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHIPMmUT72bsrGmStqgB2Raw9kv-bht5g',
    appId: '1:282800535881:ios:5596bcae3b0ca1e7d48298',
    messagingSenderId: '282800535881',
    projectId: 'migrant-connect',
    storageBucket: 'migrant-connect.firebasestorage.app',
    iosBundleId: 'com.example.migrantworker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHIPMmUT72bsrGmStqgB2Raw9kv-bht5g',
    appId: '1:282800535881:ios:5596bcae3b0ca1e7d48298',
    messagingSenderId: '282800535881',
    projectId: 'migrant-connect',
    storageBucket: 'migrant-connect.firebasestorage.app',
    iosBundleId: 'com.example.migrantworker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAynUBBnEswm2fubg1teLkazxWDow7hpgg',
    appId: '1:282800535881:web:754f367472dcc22dd48298',
    messagingSenderId: '282800535881',
    projectId: 'migrant-connect',
    authDomain: 'migrant-connect.firebaseapp.com',
    storageBucket: 'migrant-connect.firebasestorage.app',
    measurementId: 'G-M1LKZTN8DF',
  );
}
